import Edition from '@/models/Edition'

export default {
  en: [
    'introduction',
    'about-the-author',
    'on-health',
    'on-money',
    'on-relationships',
    'attention',
    'survivorship-bias',
    'omission-error',
    'part-1-happy-with-others',
    '1-relationships-should-be-mutually-beneficial',
    'part-2-happy-with-self',
    'physical-energy',
    'ignorance-is-fatal',
    'part-3-rational-thinking',
    'saving-lives',
    'part-4-launching-it-business',
    'to-those-who-read-from-the-end',
    'conclusion',
    'juliya-s-afterword',
    'nikita-s-thanks',
  ],
  ru: [
    'vvedenie',
    'ob-avtore',
    'pro-zdorove',
    'pro-dengi',
    'pro-otnosheniya',
    'vnimanie',
    'oshibka-vyzhivshego',
    'oshibka-nedoskazannosti',
    'chast-1-schastliv-s-drugimi',
    '1-otnosheniya-dolzhny-byt-vzaimovygodnymi',
    'chast-2-schastliv-s-soboy',
    'fizicheskaya-energiya',
    'nevezhestvo-fatalno',
    'chast-3-racionalnoe-myshlenie',
    'spasaem-zhizni',
    'chast-4-zapusk-it-biznesa',
    'dlya-teh-kto-chitaet-knigu-s-konca',
    'zaklyuchenie',
    'posleslovie-yulii',
    'blagodarnosti-nikity',
  ],
} as Record<Edition, string[]>
